openapi: 3.0.0
info:
  title: Todo API
  description: An API for managing todos
  version: 1.0.0
paths:
  /todos:
    get:
      summary: Get all todos
      responses:
        '200':
          description: A list of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Create a todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      responses:
        '201':
          description: Todo created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    /todos/{todo_id}:
      parameters:
        - name: todo_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      get:
        summary: Get a todo by ID
        responses:
          '200':
            description: Returns a single todo
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Todo'
          '404':
            description: Todo not found
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
      put:
        summary: Update a todo by ID
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateTodo'
        responses:
          '200':
            description: Todo updated successfully
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Todo'
          '404':
            description: Todo not found
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
      patch:
        summary: Partially update a todo by ID
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatchTodo'
        responses:
          '200':
            description: Todo updated successfully
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Todo'
          '404':
            description: Todo not found
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
      delete:
        summary: Delete a todo by ID
        responses:
          '204':
            description: Todo deleted successfully
          '400':
            description: Invalid input
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        desc:
          type: string
        is_complete:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    NewTodo:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
        description:
          type: string
    UpdateTodo:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
    PatchTodo:
      type: object
      additionalProperties:
        type: string
