apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-flask-app
  template:
    metadata:
      labels:
        app: todo-flask-app
    spec:
      containers:
        - name: todo-flask-app
          imagePullPolicy: Always  # uses latest
          image: timshee/todo-flask-app:0.1.3
          ports:
            - containerPort: 5000
          # Add environment variables if required
          # env:
          #   - name: VARIABLE_NAME
          #     value: "variable_value"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-flask-app-service
spec:
  selector:
    app: todo-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
